spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: auth
        uri: http://localhost:8010
        predicates:
        - Path=/auth/**
server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true


logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka