spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/auth/**
server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka