spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: auth
        uri: http://localhost:8010
        predicates:
          - Path=/auth/**
server:
  port: 8000


logging:
  level:
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka