spring:
  application:
    name: user
server:
  port: 8020

  datasource:
    url: jdbc:postgresql://localhost:5436/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver