spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5436/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${JWT_SECRET}

server:
  port: 8020